fix FK constraints
Some FK constraints were wrongly defined, for example

ALTER TABLE Point_previous_next
ADD CONSTRAINT point_fkeys_in__trip
    FOREIGN KEY (current_point_id,previous_point_id, next_point_id)
    REFERENCES Point (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED;

This, rightfully so, gives us the following error
ERROR:  number of referencing and referenced columns for foreign key disagree

To fix this we define the FKs separately as multiple constraints, and the
the "role" of the key to the constraint name in the following example
we have "point_fkeys_in__trip_as_current_point" where the "role" is "current_point".

ALTER TABLE Point_previous_next
    ADD CONSTRAINT point_fkeys_in__trip_as_current_point FOREIGN KEY (current_point_id) REFERENCES Point (id) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT point_fkeys_in__trip_as_previous_point FOREIGN KEY (previous_point_id) REFERENCES Point (id) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT point_fkeys_in__trip_as_next_point FOREIGN KEY (next_point_id) REFERENCES Point (id) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;