fix typo
We were doing Schema.dump() and this gave us the following error:
"""
TypeError: Schema.dump() missing 1 required positional argument: 'obj'
"""
This happens because we didn't instantiate the schema object.
The correct way is Schema().dump().