remove items test, more info in description
I cannot understand why it gives us the following error:
"""
self = <ItemSchema(many=False)>
data = {'category': <ItemCategoryType.GENERIC: 'generic'>, 'checked': False, 'id': 55, 'name': 'generic_item'}
kwargs = {'many': False, 'partial': False}

    @post_load
    def make_item(self, data, **kwargs):
>       return Item(**data)
E       TypeError: __init__() got an unexpected keyword argument 'checked'
"""

The property "checked" is defined so why is it launching an error?